# Generated by Django 5.2 on 2025-04-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر'), ('patient', 'بیمار'), ('advisor', 'مشاور')], default='patient', max_length=10),
        ),
    ]
