# Generated by Django 5.2 on 2025-04-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='apo_time',
            new_name='appointment_time',
        ),
    ]
